### ISSUE TITLE
VTK version 5

### ISSUE THREAD

**Issue by Salwathouir** [valette/Wavemesh#4]
Hello, I could not find vtk version 5. what should I do to run your project

**Comment by valette** [comment]
with this version : cbad6ae8c82d866b5ce30d427d2fa4da22a052ff
I fixed compilation on my box with vtk 6. Is it OK from your side?

**Comment by Salwathouir** [comment]
Hello Sir, i have this list of errors that i coudn't fixe it. Could you
help me please



2018-06-14 14:21 GMT+01:00 Sébastien Valette <notifications@github.com>:

**Comment by valette** [comment]
I cannot see the list of errors, did you forget to paste?

**Comment by Salwathouir** [comment]
2018-06-22 8:32 GMT+01:00 Sébastien Valette <notifications@github.com>:

**Comment by Salwathouir** [comment]
![capture](https://user-images.githubusercontent.com/38991388/41793115-083c885c-7653-11e8-972c-593c035e1d4f.PNG)

**Comment by valette** [comment]
I have just pushed a potential fix for windows : 2a45e5946a47e0cfb64505e2ecd6cfe77ac99325

**Comment by Salwathouir** [comment]
![dd](https://user-images.githubusercontent.com/38991388/42209078-afc1bf16-7ea5-11e8-8719-98031782e086.PNG)
still have this error :( help please! i just want to visualize the result

**Comment by valette** [comment]
Ok we are making progress! What about that one? d6795b02287414d192023077908d8967770faa51

**Comment by Salwathouir** [comment]
it works finallyyyy  there is  no error but when I execute the projet,  the
.exe file disappear so quickly. I added this code (  while(1){}  ) at the
end of wavemsh.cxx but it has exited with code 0

2018-07-03 10:20 GMT+01:00 Sébastien Valette <notifications@github.com>:

**Comment by valette** [comment]
This is a command line executable . To enable display use option - d 1 or - d 2
